### ISSUE TITLE
Auto complete

### ISSUE THREAD

**Issue by neuberoliveira** [jonyw4/pagarme-js-type#1]
Blz man, eu postei la no repo do pagarme.

Seguinte, para mim nao rolou nenhum autocomplete nas ides vscode e phpstorm na hora de usar o `client.connect({api_key})`, quando dou um `.` depois do connect nao da autocomplete de nada. 

Ai quera saber se passou por isso tambem, eu consegui resolver.

To mandando como ta a minha versao, que funcionou o autocomplete numa boa, so nao sei bem se esta certo, boas praticas etc. Se achar que vale a pena seguir assim eu faco a PR.

[pagarme-types.txt](https://github.com/jonyw4/pagarme-js-type/files/4954076/pagarme-types.txt)

**Comment by jonyw4** [comment]
Ok, e vou dar uma olhada pra entender o motivo de não estar andando certo no seu VSCode, porém o seu código não bate com [a documentação do pagarme](https://pagarme.github.io/pagarme-js/). Lá diz que quando você usa o `client.connect` ele retorna de volta o `client`. No seu codigo o `client.connect` retorna `Resources`.

**Comment by jonyw4** [comment]
Eu tirei alguns prints aqui do pacote instalado em um repo com Typescript 3.8.3 e VSCode 1.47.2 pra você ver como que ele fica.
### `client`
![Anotação 2020-07-21 134227](https://user-images.githubusercontent.com/14056669/88082467-31209180-cb58-11ea-9546-ba2d011b9651.png)
### const da resposta do `client.connect`
![Anotação 2020-07-21 643634634](https://user-images.githubusercontent.com/14056669/88082474-32ea5500-cb58-11ea-9668-d875ec0da86c.png)

**Comment by jonyw4** [comment]
Vou dar como fechado. Qualquer coisa só mandar msg aqui
