### ISSUE TITLE
Não está sendo encontrado no NPM

### ISSUE THREAD

**Issue by vlosito** [jonyw4/pagarme-js-type#5]
Bom dia,
Tentei usar sua biblioteca mas ao tentar instalar ele deu um erro de que não existe no repositório do NPM

npm ERR! 404 Not Found - GET https://registry.npmjs.org/pagarme-js-types - Not found
npm ERR! 404 
npm ERR! 404  'pagarme-js-types@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by jonyw4** [comment]
Oi, vc digitou o nome do repositório errado. Ele n tem o "s" no final de type

**Comment by vlosito** [comment]
OK, obrigado, deu certo, só uma observação no seu readme está com s no final de type

**Comment by jonyw4** [comment]
@vlosito, obg por me avisar pelo problema, eu percebi que eu tinha me engano no nome e digitado errado mesmo.  O certo seria com s no final. Então fiz algumas coisas:
1. Renomeei o repositório
2. [ Descontinuei o `pagarme-js-type` no NPM](https://www.npmjs.com/package/pagarme-js-type) 
3. [Publiquei a versão v2.0 usando `pagarme-js-types` ](https://www.npmjs.com/package/pagarme-js-types)

Faz um tempinho que não atualizo o projeto. Deixei apenas com as tipagens da parte que estou usando do pagarme. Se desejar mais pode abrir um PR ou uma issue. Abraços!
